extends:
  - eslint-config-airbnb
  - prettier
  - prettier/react
  - prettier/flowtype
  - plugin:flowtype/recommended

plugins:
    - prettier
    - flowtype
    - jest

parser:
  babel-eslint

settings:
  ecmascript: 6

parserOptions:
  sourceType: "module"
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true

env:
  browser: true
  jest: true

rules:
  jest/no-disabled-tests: "warn"
  jest/no-focused-tests: "error"
  jest/no-identical-title: "error"
  jest/prefer-to-have-length: "warn"
  jest/valid-expect: "error"
  # indent: 2
  func-style: 0
  func-names: 0
  comma-dangle: 0
  no-console: 0
  no-param-reassign: 0
  linebreak-style: 0
  object-shorthand: 0
  no-underscore-dangle: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/extensions: 0
  react/jsx-filename-extension: 0
  react/prefer-stateless-function: 0
  react/no-children-prop: 0
  react/forbid-prop-types: 0
  react/prop-types: 0
  prettier/prettier: ["error", {"trailingComma": "es5", "singleQuote": true, "printWidth": 120}]
